export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const REORDER_INGREDIENTS: 'REORDER_INGREDIENTS' = 'REORDER_INGREDIENTS';
export const CLEAN_STATE: 'CLEAN_STATE' = 'CLEAN_STATE';


export const BURGER_DATA_REQUEST: 'BURGER_DATA_REQUEST' = 'BURGER_DATA_REQUEST';
export const BURGER_DATA_SUCCESS: 'BURGER_DATA_SUCCESS' = 'BURGER_DATA_SUCCESS';
export const BURGER_DATA_ERROR: 'BURGER_DATA_ERROR' = 'BURGER_DATA_ERROR';
export const ADD_AMMOUNT: 'ADD_AMOUNT' = 'ADD_AMOUNT';
export const DECREASE_AMOUNT: 'DECREASE_AMOUNT' = 'DECREASE_AMOUNT';
export const CLEAN_INGREDIENTS_AMOUNTS: 'CLEAN_INGREDIENTS_AMOUNTS' = 'CLEAN_INGREDIENTS_AMOUNTS';


export const CLICK_ON_INGREDIENT: 'CLICK_ON_INGREDIENT' = 'CLICK_ON_INGREDIENT';
export const CLICK_ON_CLOSE_BUTTON: 'CLICK_ON_CLOSE_BUTTON' = 'CLICK_ON_CLOSE_BUTTON';


export const OPEN_ORDER_POPUP: 'OPEN_ORDER_POPUP' = 'OPEN_ORDER_POPUP';
export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR: 'GET_ORDER_ERROR' = 'GET_ORDER_ERROR';
export const CLOSE_ORDER_POPUP: 'CLOSE_ORDER_POPUP' = 'CLOSE_ORDER_POPUP';

export const RESET_REQUEST: 'RESET_REQUEST' = 'RESET_REQUEST';
export const RESET_SUCCESS: 'RESET_SUCCESS' = 'RESET_SUCCESS';
export const RESET_ERROR: 'RESET_ERROR' = 'RESET_ERROR';


export const SET_PASSWORD_REQUEST: 'SET_PASSWORD_REQUEST' = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS: 'SET_PASSWORD_SUCCESS' = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR' = 'SET_PASSWORD_ERROR';

export const CREATE_USER_REQUEST: 'CREATE_USER_REQUEST' = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS' = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR: 'CREATE_USER_ERROR' = 'CREATE_USER_ERROR';

export const LOGIN_REQUEST: 'lOGIN_REQUEST' = 'lOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_ERROR: 'LOGIN_ERROR' = 'LOGIN_ERROR';

export const USER_DATA_REQUEST: ' USER_DATA_REQUEST' = ' USER_DATA_REQUEST';
export const USER_DATA_SUCCESS: 'USER_DARA_SUCCESS' = 'USER_DARA_SUCCESS';
export const USER_DATA_ERROR: ' USER_DATA_ERROR' = ' USER_DATA_ERROR';

export const CHANGE_NAME: 'CHANGE_NAME' = 'CHANGE_NAME';
export const CHANGE_EMAIL: 'CHANGE_EMAIL' = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD: 'CHANGE_PASSWORD' = 'CHANGE_PASSWORD';


export const USER_LOGOUT: 'USER_LOGOUT' = 'USER_LOGOUT';


export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_CLOSE_CONNECTION: 'WS_CLOSE_CONNECTION' = 'WS_CLOSE_CONNECTION';

export const WS_AUTH_CONNECTION_SUCCESS: 'WS_AUTH_CONNECTION_SUCCESS' = 'WS_AUTH_CONNECTION_SUCCESS';
export const WS_AUTH_CONNECTION_ERROR: 'WS_AUTH_CONNECTION_ERROR' = 'WS_AUTH_CONNECTION_ERROR';
export const WS_AUTH_CONNECTION_GET_MESSAGE: ' WS_AUTH_CONNECTION_GET_MESSAGE' = ' WS_AUTH_CONNECTION_GET_MESSAGE';
export const WS_AUTH_CONNECTION_START: ' WS_AUTH_CONNECTION_START' = ' WS_AUTH_CONNECTION_START';
export const CLICK_ON_ORDER: 'CLICK_ON_ORDER' = 'CLICK_ON_ORDER';



